Week 5, Assignment C1:

Logistic Regression with Yahoo! Finance API in Python

In this notebook, we will study Logistic Regression using the Yahoo! Finance API in Python.

Please complete the lines bellow where you see "#TODO".

In [1]:

!pip install yfinance


In [2]:

import numpy as np
import pandas as pd
import yfinance as yf

#Our work will also require some components of the Sklearn and Pandas_Datareader packages as imported below:

from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from pandas_datareader import data as pdr
yf.pdr_override()




In [3]:
#Objective 2.
#Select a stock symbol for a stock whose historical data is available on the Yahoo! Finance website.  Store the
#string of your chosen symbol to the new variable "stock_symbol".

stock_symbol = "AAPL"

In [4]:
#Objective 3.
#Use the function "pdr.get_data_yahoo(stock_symbol, start_date, end_date)" to generate a Pandas dataframe of
#historical stock data for your chosen stock.  Retain only the first four columns of the dataframe.  Be sure to 
#drop any rows containing NaN's, and take a peek at the resulting dataframe to make sure everything looks good.

df = yf.download(stock_symbol, "2018-12-31", "2021-1-1")
df = df[["Open","High","Low", "Close"]]
df= df.dropna()

[*********************100%***********************]  1 of 1 completed


In [5]:
df

Open        High         Low       Close
Date                                                      
2018-12-31   39.632500   39.840000   39.119999   39.435001
2019-01-02   38.722500   39.712502   38.557499   39.480000
2019-01-03   35.994999   36.430000   35.500000   35.547501
2019-01-04   36.132500   37.137501   35.950001   37.064999
2019-01-07   37.174999   37.207500   36.474998   36.982498
...                ...         ...         ...         ...
2020-12-24  131.320007  133.460007  131.100006  131.970001
2020-12-28  133.990005  137.339996  133.509995  136.690002
2020-12-29  138.050003  138.789993  134.339996  134.869995
2020-12-30  135.580002  135.990005  133.399994  133.720001
2020-12-31  134.080002  134.740005  131.720001  132.690002

[506 rows x 4 columns]

In [6]:
#Objective 4.
#Use the historical data to define some predictor variables.  Add these variables to the dataframe.  Include, at a
#minimum, (Predictor.I) the rolling average closing price over the past fifteen (15) days and (Predictor.II) the
#change in opening price over the past one (1) day.  Be sure to again drop any rows containing NaN's, and take a
#peek at the resulting dataframe to make sure everything looks good.  Store the dataframe as the new variable "X".

df['Close_15_Rolling'] = df["Close"].rolling(window=15).mean()
df['Open_1_Change'] = df["Open"].diff(-1)
df = df.dropna()
X = df

In [16]:
#Objective 5.
#Define the target or dependent variable to be one (1) if the change in closing price over the past one (1) day is
#nonnegative and negative one (-1) if the change in closing price over the past one (1) day is negative.  This
#variable's values should be forward-looking (i.e., you should subtract today's price from tomorrow's price rather
#than subtracting yesterday's price from today's price).  Store the resulting values as the new variable "y".  You
#may find the "np.where(*args)" function to be useful.  Look it up in Numpy documentation for support.

y = np.where(df["Close"].shift(-1)- df['Close']>=0,1,-1)
y

array([ 1, -1,  1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1, -1,  1,
       -1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1, -1,  1,  1,  1,
        1,  1,  1,  1, -1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1, -1,
        1, -1,  1, -1, -1,  1, -1, -1, -1,  1,  1, -1, -1, -1,  1, -1, -1,
       -1, -1, -1,  1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1,  1,
       -1,  1, -1, -1, -1,  1, -1, -1,  1,  1,  1, -1, -1,  1,  1, -1,  1,
        1, -1, -1,  1, -1,  1,  1, -1, -1,  1,  1, -1,  1, -1, -1, -1,  1,
        1,  1, -1, -1,  1, -1, -1,  1,  1,  1,  1, -1, -1,  1, -1,  1,  1,
       -1, -1,  1,  1, -1,  1,  1,  1, -1, -1,  1,  1,  1, -1, -1,  1, -1,
        1, -1, -1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1,
        1,  1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1, -1,  1,  1,  1,  1,
       -1,  1, -1,  1,  1, -1, -1, -1, -1,  1, -1,  1, -1, -1, -1,  1,  1,
        1, -1,  1,  1,  1

In [8]:
#Objective 6.
#Split the data into training and test sets, putting the first seventy percent (70%) of the data in the training
#set.

index = int(0.7*len(X))
X_train = X[:index]
X_test = X[index:]
y_train = y[:index]
y_test = y[index:]

In [9]:
#Objective 7.
#Instantiate the Logistic Regression model object, and use its ".fit(*args)" method to fit the model to the 
#training data.

logistic = LogisticRegression()
logistic = logistic.fit (X_train ,y_train )

In [10]:
#Objective 8.
#Examine the model's coefficients by using its ".coef_" method.

pd.DataFrame(zip(X.columns, np.transpose(logistic.coef_)))

0                        1
0              Open     [2.2739354963337535]
1              High    [-0.4637676765617744]
2               Low     [0.1513331214327968]
3             Close    [-1.9391331467323456]
4  Close_15_Rolling  [-0.012720448010320627]
5     Open_1_Change     [-1.643646609169298]

In [11]:
#Objective 9.
#Use the model's ".predict_proba(*args)" and ".predict(*args)" methods to generate predictions over the test set.

probabilities = logistic.predict_proba(X_test)
predictions = logistic.predict(X_test)

In [19]:
#Objective 10.
#Use the function "metrics.confusion_matrix(*args)" to create a confusion matrix comparing the predicted and true
#classification labels over the test set.

#sklearn.metrics.confusion_matrix(y_pred = predictions,y_true =y_test)
metrics.confusion_matrix( y_test , predictions)

array([[29, 35],
       [16, 68]], dtype=int64)

In [24]:
 #print(sklearn.metrics.roc_auc_score(y_test, probabilities[:1]))

In [25]:
#Objective 11.
#Calculate the model's accuracy on the test set using its ".score(*args)" method.

logistic.score(X_test,y_test)

0.6554054054054054

In [29]:
#Objective 12.
#Use five-fold cross validation to cross-check the accuracy of the model over different held-out test sets.  This
#is where you should use the function "cross_val_score(*args)".

cross_val = cross_val_score(logisticRedrisson, X_test, y_test, cv=5)

C:\Users\beem2\OneDrive\Attachments\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\beem2\OneDrive\Attachments\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logisti

In [27]:
cross_val

array([0.56666667, 0.76666667, 0.7       , 0.72413793, 0.62068966])

In [28]:
cross_val.mean()

0.6756321839080459